-- INSERT INTO books SET title = '구운몽전',writer = '운몽이',content = '꿈을 꾸었네...';
-- UPDATE books SET title = '별주부전', writer ='거북이', content = '죽다 살았네...' WHERE id=3;
-- DELETE FROM books WHERE id=4;
-- SELECT title, writer FROM books;
-- SELECT * FROM books;
-- SELECT * FROM books ORDER BY id ASC;
-- SELECT * FROM books ORDER BY id DESC;
-- SELECT * FROM books WHERE id=3;
-- SELECT * FROM books ORDER by id DESC LIMIT 1, 3;
-- SELECT COUNT(id) FROM books;
-- SELECT*FROM books ORDER BY id DESC;
-- 1pafe 쿼리
-- SELECT * FROM books ORDER BY id DESC LIMIT 3, 3;
-- INSERT INTO users SET userid='karen2306',userpw='0000',username='이예솔',email= 'karen2306@naver.com';
SELECT * FROM users WHERE userid LIKE '%kar%';